package com.springapp;

import javax.persistence.*;

//specify name which will be used for this entity within this app
//also specify DB table name which matches this model
@Entity(name = "storageboxes")
@Table(name = "storageboxes")
public class StorageBoxes {
    @Column(name = "category", nullable = false)
    private String category;

    @Column(name = "folder", nullable = false)
    private String folder;

    @Column(name = "tags", nullable = false)
    private String tags;

    @Column(name = "file", nullable = false)
    private String file;

    @Column(name = "myid", nullable = false)
    private Integer myid;

    //IMPORTANT: always name the @Id annotated index as "id" in the DB table
    //do not try to call it something else.  after debugging, found SQL generated by Spring always used "id"
    //regardless of how it was renamed here
    @Column(name = "id", nullable = false)
    public Integer id;

    public StorageBoxes() {
    }

    @Override
    public String toString()
    {
        String returnStr;
        returnStr="Category,"+category+",folder,"+folder+",tags,"+tags+",file,"+file+",id,"+id+",myid,"+myid+"\n";
        return returnStr;
    }

    public StorageBoxes(String category, String folder, String tags, String filenm, Integer myid) {
        this.category = category;
        this.folder = folder;
        this.tags = tags;
        this.file = filenm;
        this.myid = myid;
    }

    //IMPORTANT: always name the @Id annotated index as "id" in the DB table
    //do not try to call it something else.  after debugging, found SQL generated by Spring always used "id"
    //regardless of how it was renamed here
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }

    public String getCategory() {
        return category;
    }

    public String getFolder() {
        return folder;
    }

    public String getTags() {
        return tags;
    }

    public String getFile() {
        return file;
    }
    public void setCategory(String category) {
        this.category = category;
    }

    public void setFolder(String folder) {
        this.folder = folder;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public void setFile(String file) {
        this.file = file;
    }

    public Integer getMyid() {
        return myid;
    }

    public void setMyid(Integer myid) {
        this.myid = myid;
    }
}

